version: '3.8'

services:
  backend_rds:
    env_file:
    - vars.env
    image: 194722414339.dkr.ecr.eu-north-1.amazonaws.com/project1-backend:backend-rds
    container_name: backend_rds
    ports:
      - "8000:8000"
    networks:
      - backend
    entrypoint: ["sh", "-c", "sleep 10 && python manage.py runserver 0.0.0.0:8000"]

  backend_redis:
    env_file:
    - vars.env
    image: 194722414339.dkr.ecr.eu-north-1.amazonaws.com/project1-backend:backend-redis
    container_name: backend_redis
    ports:
      - "8003:8003"
    networks:
      - backend
    entrypoint: ["sh", "-c", "sleep 10 && python manage.py runserver 0.0.0.0:8003"]

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
    driver: local