version: '3'

services:
  frontend:
    image: nginx:latest
    container_name: frontend
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"


  db:
    image: postgres:14-alpine
    container_name: db
    environment:
      POSTGRES_DB: "mydatabase"
      POSTGRES_USER: "myuser"
      POSTGRES_PASSWORD: "mypassword"
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: "mypassword"
    command: redis-server --requirepass "mypassword"

  backend_rds:
    build: ./backend_rds
    container_name: backend_rds
    volumes:
      - ./backend_rds:/app
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: "your-secret-key-here"
      DEBUG: false
      DB_NAME: "mydatabase"
      DB_USER: "myuser"
      DB_PASSWORD: "mypassword"
      DB_HOST: db
      DB_PORT: 5432
      CORS_ALLOWED_ORIGINS: "http://localhost"
    depends_on:
      - db

  backend_redis:
    build: ./backend_redis
    container_name: backend_redis
    volumes:
      - ./backend_redis:/app
    ports:
      - "8003:8003"
    environment:
      SECRET_KEY: "your-secret-key-here"
      DEBUG: false
      CORS_ALLOWED_ORIGINS: "http://localhost"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: "0"
      REDIS_PASSWORD: "mypassword"
    depends_on:
      - redis

