version: '3'

services:
  frontend:
    image: nginx:latest
    container_name: frontend
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "8080:80"


  db:
    image: postgres:14-alpine
    container_name: db
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "mypassword"]
    # environment:
    #   REDIS_DB: "0"  # Redis doesn't use environment variables for DB; use commands in code to switch DB.

  backend_rds:
    build: ./backend_rds
    container_name: backend_rds
    # command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend_rds:/app
    ports:
      - "8000:8000"
    environment:
      DB_NAME: "mydatabase"
      DB_USER: "myuser"
      DB_PASSWORD: "mypassword"
      DB_HOST: "db"
      CORS_ALLOWED_ORIGINS: "http://frontend:8080"
    depends_on:
      - db

  backend_redis:
    build: ./backend_redis
    container_name: backend_redis
    volumes:
      - ./backend_redis:/app
    ports:
      - "8003:8003"
    environment:
      CORS_ALLOWED_ORIGINS: "http://frontend:8080"
      REDIS_HOST: "redis"
      REDIS_PORT: 6379
      REDIS_DB: "0"
      REDIS_PASSWORD: "mypassword"
    depends_on:
      - redis

