name: Deploy Project
on: 
  workflow_dispatch:
jobs:

  deploy-to-ecr:
    uses: ./.github/workflows/deploy-to-ecr.yml
    secrets:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}

  deploy-frontend:
    uses: ./.github/workflows/deploy-frontend.yml

  deploy-backend:
    needs: 
    - deploy-frontend
    - deploy-to-ecr
    uses: ./.github/workflows/deploy-backend.yml
