name: Deploy Frontend, Backend and Docker Images to ECR
on: 
  workflow_dispatch:
jobs:
  deploy-to-ecr:
    uses: ./.github/workflows/deploy-to-ecr.yml

  deploy-frontend:
    uses: ./.github/workflows/deploy-frontend.yml

  deploy-backend:
    needs: 
    - deploy-frontend
    - deploy-to-ecr
    uses: ./.github/workflows/deploy-backend.yml
    