name: Deploy Project
on: 
  workflow_dispatch:
jobs:

  deploy-to-ecr:
    uses: ./.github/workflows/deploy-to-ecr.yml
    secrets:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

  deploy-frontend:
    uses: ./.github/workflows/deploy-frontend.yml

  deploy-backend:
    needs: 
    - deploy-frontend
    - deploy-to-ecr
    uses: ./.github/workflows/deploy-backend.yml
